import { describe, it, expect, beforeEach, afterEach } from "bun:test"
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync } from "fs"
import { tmpdir } from "os"
import { join } from "path"
import { generateCommands } from "../commands"
import type { CliDispatchConfig } from "../config"

let dir: string

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "cli-dispatch-commands-test-"))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

function configWith(...names: string[]): CliDispatchConfig {
  const delegates: CliDispatchConfig["delegates"] = {}
  for (const name of names) {
    delegates[name] = {
      binary: name,
      parser: "raw",
      startArgs: ["{prompt}"],
      replyArgs: ["{prompt}"],
    }
  }
  return { delegates }
}

describe("generateCommands", () => {
  it("does not hardcode /codex or /cc in the description of a custom delegate", () => {
    generateCommands(configWith("gemini"), dir)
    const content = readFileSync(join(dir, "gemini.md"), "utf-8")

    expect(content).not.toContain("/codex")
    expect(content).not.toContain("/cc")
    expect(content).toContain("gemini")
  })

  it("names the other configured delegates in the generated description", () => {
    generateCommands(configWith("claude", "gemini"), dir)
    const content = readFileSync(join(dir, "gemini.md"), "utf-8")

    expect(content).toContain("/claude")
    expect(content).not.toContain("/codex")
  })

  it("marks every generated file as generated by opencode-cli-dispatch", () => {
    generateCommands(configWith("claude"), dir)

    for (const file of ["claude.md", "opencode.md"]) {
      expect(readFileSync(join(dir, file), "utf-8")).toContain(
        "<!-- generated by opencode-cli-dispatch -->",
      )
    }
  })

  it("deletes a previously generated command file whose delegate is no longer configured", () => {
    generateCommands(configWith("claude", "codex"), dir)
    generateCommands(configWith("claude"), dir)

    expect(existsSync(join(dir, "codex.md"))).toBe(false)
    expect(existsSync(join(dir, "claude.md"))).toBe(true)
    expect(existsSync(join(dir, "opencode.md"))).toBe(true)
  })

  it("declares the target delegate structurally in frontmatter", () => {
    generateCommands(configWith("claude"), dir)

    const claude = readFileSync(join(dir, "claude.md"), "utf-8")
    expect(claude).toMatch(/^---\n[\s\S]*?\ndelegate: claude\n[\s\S]*?---/)
    const opencode = readFileSync(join(dir, "opencode.md"), "utf-8")
    expect(opencode).not.toContain("delegate:")
  })

  it("never deletes a command file without the generated marker", () => {
    writeFileSync(join(dir, "cc.md"), "manually maintained alias\n", "utf-8")

    generateCommands(configWith("claude"), dir)

    expect(readFileSync(join(dir, "cc.md"), "utf-8")).toBe("manually maintained alias\n")
  })

  it("is idempotent: a second run leaves file contents and mtimes unchanged", async () => {
    generateCommands(configWith("claude"), dir)
    const first = readFileSync(join(dir, "claude.md"), "utf-8")
    const stat1 = (await import("fs")).statSync(join(dir, "claude.md")).mtimeMs
    await new Promise((r) => setTimeout(r, 20))
    generateCommands(configWith("claude"), dir)
    const stat2 = (await import("fs")).statSync(join(dir, "claude.md")).mtimeMs
    expect(readFileSync(join(dir, "claude.md"), "utf-8")).toBe(first)
    expect(stat2).toBe(stat1)
  })

  it("generates a cc.md alias when a claude delegate is configured", () => {
    generateCommands(configWith("claude"), dir)
    const cc = readFileSync(join(dir, "cc.md"), "utf-8")
    expect(cc).toContain("delegate: claude")
    expect(cc).toContain("Alias")
  })

  it("never overwrites a hand-maintained cc.md (no generated marker)", () => {
    writeFileSync(join(dir, "cc.md"), "# my custom cc command\n")
    generateCommands(configWith("claude"), dir)
    expect(readFileSync(join(dir, "cc.md"), "utf-8")).toBe("# my custom cc command\n")
  })

  it("includes a tool-availability guard in every delegate command", () => {
    generateCommands(configWith("claude", "codex"), dir)

    const claude = readFileSync(join(dir, "claude.md"), "utf-8")
    expect(claude).toContain("Tool availability check")
    expect(claude).toContain("claude_start")
    expect(claude).toContain("restart opencode")

    const cc = readFileSync(join(dir, "cc.md"), "utf-8")
    expect(cc).toContain("Tool availability check")
    expect(cc).toContain("claude_start")

    const codex = readFileSync(join(dir, "codex.md"), "utf-8")
    expect(codex).toContain("Tool availability check")
    expect(codex).toContain("codex_start")
  })

  it("does not add the guard to the /opencode exit command", () => {
    generateCommands(configWith("claude"), dir)
    const content = readFileSync(join(dir, "opencode.md"), "utf-8")
    expect(content).not.toContain("Tool availability check")
  })

  it("removes a stale generated cc.md when claude is no longer configured", () => {
    generateCommands(configWith("claude"), dir)
    expect(existsSync(join(dir, "cc.md"))).toBe(true)
    generateCommands(configWith("codex"), dir)
    expect(existsSync(join(dir, "cc.md"))).toBe(false)
  })
})
