import { describe, it, expect, beforeEach, afterEach } from "bun:test"
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync } from "fs"
import { tmpdir } from "os"
import { join } from "path"
import { generateCommands } from "../commands"
import type { CliDispatchConfig } from "../config"

let dir: string

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "cli-dispatch-commands-test-"))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

function configWith(...names: string[]): CliDispatchConfig {
  const delegates: CliDispatchConfig["delegates"] = {}
  for (const name of names) {
    delegates[name] = {
      binary: name,
      parser: "raw",
      startArgs: ["{prompt}"],
      replyArgs: ["{prompt}"],
    }
  }
  return { delegates }
}

describe("generateCommands", () => {
  it("does not hardcode /codex or /cc in the description of a custom delegate", () => {
    generateCommands(configWith("gemini"), dir)
    const content = readFileSync(join(dir, "gemini.md"), "utf-8")

    expect(content).not.toContain("/codex")
    expect(content).not.toContain("/cc")
    expect(content).toContain("gemini")
  })

  it("names the other configured delegates in the generated description", () => {
    generateCommands(configWith("claude", "gemini"), dir)
    const content = readFileSync(join(dir, "gemini.md"), "utf-8")

    expect(content).toContain("/claude")
    expect(content).not.toContain("/codex")
  })

  it("marks every generated file as generated by opencode-cli-dispatch", () => {
    generateCommands(configWith("claude"), dir)

    for (const file of ["claude.md", "opencode.md"]) {
      expect(readFileSync(join(dir, file), "utf-8")).toContain(
        "<!-- generated by opencode-cli-dispatch -->",
      )
    }
  })

  it("deletes a previously generated command file whose delegate is no longer configured", () => {
    generateCommands(configWith("claude", "codex"), dir)
    generateCommands(configWith("claude"), dir)

    expect(existsSync(join(dir, "codex.md"))).toBe(false)
    expect(existsSync(join(dir, "claude.md"))).toBe(true)
    expect(existsSync(join(dir, "opencode.md"))).toBe(true)
  })

  it("never deletes a command file without the generated marker", () => {
    writeFileSync(join(dir, "cc.md"), "manually maintained alias\n", "utf-8")

    generateCommands(configWith("claude"), dir)

    expect(readFileSync(join(dir, "cc.md"), "utf-8")).toBe("manually maintained alias\n")
  })
})
