import { describe, it, expect } from "bun:test"
import { GENERATED_MARKER, EXTERNAL_ID_RE, isValidExternalId, validateArgvInjection } from "../policy"

describe("GENERATED_MARKER", () => {
  it("keeps its exact value", () => {
    expect(GENERATED_MARKER).toBe("<!-- generated by opencode-cli-dispatch -->")
  })
})

describe("isValidExternalId", () => {
  it("accepts ses_-style ids, UUIDs, and 8-char minimum ids", () => {
    expect(isValidExternalId("ses_abc12345")).toBe(true)
    expect(isValidExternalId("3f6c9d2e-1a2b-4c3d-8e4f-5a6b7c8d9e0f")).toBe(true)
    expect(isValidExternalId("abcdefgh")).toBe(true)
    expect(EXTERNAL_ID_RE.source).toBe("^[A-Za-z0-9_-]{8,128}$")
  })

  it("rejects too-short, too-long, and flag/injection-shaped ids", () => {
    expect(isValidExternalId("short")).toBe(false)
    expect(isValidExternalId("a".repeat(129))).toBe(false)
    expect(isValidExternalId("-p rm -rf")).toBe(false)
    expect(isValidExternalId("--flag=value")).toBe(false)
    expect(isValidExternalId("id with spaces")).toBe(false)
    expect(isValidExternalId("")).toBe(false)
  })
})

describe("validateArgvInjection", () => {
  it("accepts the claude built-in argvs", () => {
    const start = ["-p", "--output-format", "stream-json", "--verbose", "--permission-mode", "acceptEdits", "--session-id", "{sessionId}", "--", "{prompt}"]
    const reply = ["-p", "--output-format", "stream-json", "--verbose", "--permission-mode", "acceptEdits", "--resume", "{externalId}", "--", "{prompt}"]
    expect(validateArgvInjection("claude", "startArgs", start)).toBeUndefined()
    expect(validateArgvInjection("claude", "replyArgs", reply)).toBeUndefined()
  })

  it("accepts the codex built-in replyArgs (session id and prompt as trailing positionals)", () => {
    const reply = ["exec", "resume", "--json", "-c", "sandbox_mode=workspace-write", "--skip-git-repo-check", "--", "{externalId}", "{prompt}"]
    expect(validateArgvInjection("codex", "replyArgs", reply)).toBeUndefined()
  })

  it("accepts the opencode adapter built-in argvs", () => {
    const start = ["run", "--format", "json", "--", "{prompt}"]
    const reply = ["run", "--format", "json", "-s", "{externalId}", "-c", "--", "{prompt}"]
    expect(validateArgvInjection("opencode", "startArgs", start)).toBeUndefined()
    expect(validateArgvInjection("opencode", "replyArgs", reply)).toBeUndefined()
  })

  it("rejects {prompt} without a preceding literal --", () => {
    const err = validateArgvInjection("bad", "startArgs", ["-p", "{prompt}"])
    expect(err).toContain('delegate "bad"')
    expect(err).toContain('"startArgs"')
    expect(err).toContain('"--"')
  })

  it("rejects a bare positional {externalId} (no -- and no preceding flag)", () => {
    const err = validateArgvInjection("bad", "replyArgs", ["exec", "resume", "{externalId}", "--", "{prompt}"])
    expect(err).toContain("{externalId}")
  })

  it("rejects {externalId} embedded in a larger argument", () => {
    const err = validateArgvInjection("bad", "replyArgs", ["--sid={externalId}", "--", "{prompt}"])
    expect(err).toContain('exactly "{externalId}"')
  })
})
