// Host-agnostic policy primitives shared by the OpenCode plugin and the
// Claude Code adapter. These live outside src/commands.ts so host modules
// can depend on policy without importing command generation (design D6).

// Marks files written by generateCommands so stale ones can be cleaned up on
// regeneration without ever touching hand-maintained command files. Also used
// by the prompt-sanitization checks to detect a whole command template
// mistakenly forwarded as a tool's `prompt` argument.
export const GENERATED_MARKER = "<!-- generated by opencode-cli-dispatch -->"

// Conservative shape for parser-reported delegate session ids (design D4):
// long enough to be a real id, restricted to characters that cannot break
// argv or JSON handling. A reported id outside this pattern is ignored.
export const EXTERNAL_ID_RE = /^[A-Za-z0-9_-]{8,128}$/

export function isValidExternalId(id: string): boolean {
  return EXTERNAL_ID_RE.test(id)
}

// Argv injection guard (design D4). Returns an error string, or undefined
// when the args are safe.
// Rule 1: a literal "--" must appear before any argument containing {prompt}
//   — the prompt is free text and must never be parsed as flags.
// Rule 2: an argument containing {externalId} must be exactly "{externalId}"
//   and must either follow a literal "--" or be the value of an immediately
//   preceding flag token (e.g. "--resume {externalId}"), so a substituted id
//   is never re-parsed as a new flag.
export function validateArgvInjection(name: string, argsKey: "startArgs" | "replyArgs", args: string[]): string | undefined {
  const separatorIndex = args.indexOf("--")

  const promptIndex = args.findIndex((a) => a.includes("{prompt}"))
  if (promptIndex >= 0 && (separatorIndex < 0 || separatorIndex > promptIndex)) {
    return `delegate "${name}": "${argsKey}" must place a literal "--" before the argument containing {prompt}, otherwise prompt text starting with "-" would be parsed as flags`
  }

  for (let i = 0; i < args.length; i++) {
    if (!args[i].includes("{externalId}")) continue
    if (args[i] !== "{externalId}") {
      return `delegate "${name}": "${argsKey}" argument ${JSON.stringify(args[i])} must be exactly "{externalId}" with no surrounding text`
    }
    const afterSeparator = separatorIndex >= 0 && separatorIndex < i
    const isFlagValue = i > 0 && args[i - 1] !== "--" && args[i - 1].startsWith("-")
    if (!afterSeparator && !isFlagValue) {
      return `delegate "${name}": "${argsKey}" must place "{externalId}" after a literal "--" or directly after a flag that consumes it as a value (e.g. "--resume {externalId}")`
    }
  }

  return undefined
}

export type ModelRef = string | { providerID: string; modelID: string }

export type GateTarget = { kind: "command" | "tool"; delegate: string; tool?: string }

export type GateDecision = { allow: true } | { allow: false; reason: string }

const VERIFIED_MODEL_SEGMENT_RE = /^(\*|[\w.-]+\*?)$/

export function isValidVerifiedModelPattern(entry: unknown, mode: "provider-model" | "bare"): entry is string {
  if (typeof entry !== "string") return false
  const parts = entry.split("/")
  if (mode === "provider-model") {
    if (parts.length !== 2) return false
    return parts.every((part) => VERIFIED_MODEL_SEGMENT_RE.test(part))
  }
  return parts.length === 1 && VERIFIED_MODEL_SEGMENT_RE.test(entry)
}

function matchesSegment(actual: string, pattern: string): boolean {
  if (pattern === "*") return true
  if (pattern.endsWith("*")) return actual.startsWith(pattern.slice(0, -1))
  return actual === pattern
}

export function matchesVerifiedModel(model: ModelRef, patterns: string[]): boolean {
  return patterns.some((pattern) => {
    if (pattern.includes("/")) {
      if (typeof model === "string") return false
      const [provider, modelPattern] = pattern.split("/")
      return matchesSegment(model.providerID, provider) && matchesSegment(model.modelID, modelPattern)
    }
    const actual = typeof model === "string" ? model : model.modelID
    return matchesSegment(actual, pattern)
  })
}

function modelDisplay(model: ModelRef): string {
  return typeof model === "string" ? model : `${model.providerID}/${model.modelID}`
}

function targetLabel(target: GateTarget): { label: string; verb: string } {
  return target.kind === "command"
    ? { label: target.delegate, verb: "was not started" }
    : { label: target.tool ?? target.delegate, verb: "was blocked" }
}

export function checkDelegationGate(input: {
  target: GateTarget
  prompt?: unknown
  model?: ModelRef
  verifiedModels?: string[]
  prefix: "[plugin]" | "[cli-dispatch]"
}): GateDecision {
  if (typeof input.prompt === "string" && input.prompt.includes(GENERATED_MARKER)) {
    const tool = input.target.tool ?? input.target.delegate
    return {
      allow: false,
      reason: `${tool} rejected: the "prompt" argument contains the whole delegate command template instead of the user's actual message. Pass only the user's text as "prompt".`,
    }
  }

  const patterns = input.verifiedModels
  if (!patterns || patterns.length === 0 || !input.model) return { allow: true }
  if (matchesVerifiedModel(input.model, patterns)) return { allow: true }

  const { label, verb } = targetLabel(input.target)
  return {
    allow: false,
    reason: `${input.prefix} The current model (${modelDisplay(input.model)}) is not on the verified-models allow-list for CLI delegation, so ${label} ${verb}. Switch to a verified model and try again.`,
  }
}
